apiVersion: v1
kind: ConfigMap
metadata:
  name: api-env
  namespace: amazra-staging
data:
  DATABASE_URL: REPLACE_ME
  REDIS_URL: REPLACE_ME
  ELASTICSEARCH_URL: REPLACE_ME
  RABBITMQ_URL: REPLACE_ME
  JWT_SECRET_KEY: REPLACE_ME
