apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: amazra-staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: amazra-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: api-env
